<Project Sdk="Microsoft.NET.Sdk">
<!--  <Import Project="../Dawnsbury.ModDawnniV3.targets" />-->
    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
  <PropertyGroup>
    <WarningsAsErrors>4014</WarningsAsErrors>
    <HideWarningsAndErrors>1998</HideWarningsAndErrors>
    <NoWarn>0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\YourApi.XML</DocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer" Version="2.14.1" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Common">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\Common.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury Days">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\Dawnsbury Days.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\MonoGame.Framework.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
